### ISSUE TITLE
报错了，咨询一下，谢谢。

### ISSUE THREAD

**Issue by jiachao-zhang** [lightjiao/vmess-to-clash#2]
sudo python ./vmess-app.py
Traceback (most recent call last):
  File "./vmess-app.py", line 5, in <module>
    from vmess2clash import get_clash_sub
  File "/Users/jia/Website/ClashX/vmess-to-clash/vmess2clash.py", line 62
    def generate_proxy_groups(proxy_groups: list, proxies: list) -> list:
                                          ^
SyntaxError: invalid syntax

**Comment by lightjiao** [comment]
请使用最新版本的python3
